id: IBE99D401
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:29:35+00:00'
last_modified: '2022-06-08T10:25:38.149051+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25985
  title: ཇི་བཞིན་བརྗོད་པའི་རྩོམ་ཡིག་ལ་འཇུག་ཚུལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8746':
      image_group_id: I5666
      title: ''
      total_pages: 168
      order: 1
      base_file: 8746.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
