id: P009355
initial_creation_type: ocr
source_metadata:
  id: bdr:W25985
  title: ཇི་བཞིན་བརྗོད་པའི་རྩོམ་ཡིག་ལ་འཇུག་ཚུལ
  author: ''
  volumes:
    7eccdba1375249b39b7aa9df9fd2ef84:
      image_group_id: I5666
      title: ''
      volume_number: 1
      total_pages: 168
      base_file: v001.txt
